language: php

php:
    - 5.3.3
    - 5.3
    - 5.4
    - 5.5

branches:
    only: master

notifications:
    email: false
    irc: "irc.iiens.net#Erebot"

before_script:
    - wget http://getcomposer.org/composer.phar
    - (which pear && pear install pear/PHP_ParserGenerator-alpha) || pyrus install pear/PHP_ParserGenerator-alpha
    - phpenv rehash
    - cp data/Parser.y src/Erebot/Module/Math/Parser.y
    - (which pear && PHP_PEAR_INSTALL_DIR="`pear config-get php_dir`" phplemon -q -s src/Erebot/Module/Math/Parser.y) || PHP_PEAR_INSTALL_DIR="`pyrus get php_dir | tail -n 1`" phplemon -q -s src/Erebot/Module/Math/Parser.y
    - if [[ "$TRAVIS_PHP_VERSION" = "5.3.3" ]]; then php composer.phar install --dev --prefer-source; fi
    - if [[ "$TRAVIS_PHP_VERSION" != "5.3.3" ]]; then php composer.phar install --dev; fi

script:
    - phpunit --bootstrap vendor/erebot/testenv/bootstrap.php tests/

