language: php

php:
    - 5.2
    - 5.3.2
    - 5.3
    - 5.4

branches:
    only: master

notifications:
    email: false
    irc: "irc.iiens.net#Erebot"

before_script:
    - git submodule update --init
    - (which pear && pear install pear/PHP_ParserGenerator-alpha) || pyrus install pear/PHP_ParserGenerator-alpha
    - phpenv rehash
    - cp data/Parser.y src/Erebot/Module/Math/Parser.y
    - (which pear && PHP_PEAR_INSTALL_DIR="`pear config-get php_dir`" phplemon -q -s src/Erebot/Module/Math/Parser.y) || PHP_PEAR_INSTALL_DIR="`pyrus get php_dir | tail -n 1`" phplemon -q -s src/Erebot/Module/Math/Parser.y

script: phpunit --bootstrap tests/testenv/bootstrap.php tests/

